apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipl-cricket-ingress
  namespace: ipl-cricket
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ipl-cricket.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ipl-cricket-service
            port:
              number: 80
